[CI/Build]: make it possible to build with a free-threaded interpreter
For Python 3.13/3.14, free-threaded Python does not support using the
Limited C API and the Stable ABI.

Without this change, the build ends with:
```
  In file included from /path/to/vllm/csrc/core/registration.h:3,
                   from /path/to/vllm/csrc/cpu/torch_bindings.cpp:3:
  /..../include/python3.14t/Python.h:51:4: error: #error "The limited API is not currently supported in the free-threaded build"
```

Signed-off-by: Ralf Gommers <ralf.gommers@gmail.com>